config/routes.rb
Rails.application.routes.draw do
  resources :tweets
#  get '/tweets/index', to:'tweets#index'
  root 'tweets#index'
#  get '/tweets/new', to:'tweets#new'
#  post '/tweets', to:'tweets#create'
#  delete '/tweets/:id', to:'tweets#destroy'
#  get 'tweets/:id', to:'tweets#show'
#  get 'tweets/:id/edit', to:'tweets#edit'
#  patch 'tweets/:id', to:'tweets#update'
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets=Tweet.all
  end
  
  def new
    @tweet = Tweet.new
  end
  
  def create
    
    tweet =Tweet.new(message:params[:tweet][:message], tdate: Time.current)
    tweet.save
     redirect_to root_path
  end
   
  def destroy
     tweet = Tweet.find(params[:id])
     tweet.destroy
     redirect_to root_path
  end
  
  def show
    @tweet =Tweet.find(params[:id])
  end
  
  def edit
    @tweet = Tweet.find(params[:id])
  end
  
  def update
    tweet = Tweet.find(params[:id])
    tweet.message=params[:tweet][:message]
    tweet.save
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweet_helper.rb
module TweetHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
    <div id="header">
      <%= render "header" %>
    </div>
    <div id="sidebar">
      <%= render "sidebar" %>
    </div>
    <div id="content">
      <%= yield %>
    </div>
    <div id="footer">
      <%= render "footer" %>
    </div>
    <div pageSub>
      
    </div>
  </div>
</body>
</html>

app/views/tweets/_footer.html.erb
<head>
  <title>Twap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
 <div id="newtweet">
      <p class="btn"><%= link_to 'つぶやく', new_tweet_path %></p>
 </div>

app/views/tweets/_form.html.erb
 <%= f.label :message, 'メッセージ' %>
 <%= f.text_field :message %>
 <%= f.submit '送信' %>

 

app/views/tweets/_header.html.erb
<p>TwitterもどきAPP</p>

app/views/tweets/_sidebar.html.erb
<head>
    <meta charset="utf-8">
    <link href="style.css" rel="stylesheet">
</head>
 <div id="profile">
     <p>プロフィールのようなもの</p>
 </div>

app/views/tweets/edit.html.erb
<%= form_for @tweet, url:{action: :update} do |f| %>
 <%= render "form", f: f %>
<% end %>

app/views/tweets/index.html.erb
<% @tweets.each do |tw| %>
<head>
  <title>Twap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<dvi id="tweet">
 <p>
    <%= tw.message %>
    <%= (Time.current-tw.tdate).to_i/60%>分前
    <%= link_to '削除', tweet_path(tw), method: :delete %>
    <%= link_to '表示', tweet_path(tw) %>
    <%= link_to '編集', edit_tweet_path(tw) %>
 </p>
</dvi>

<% end %>

app/views/tweets/new.html.erb
<%= form_for @tweet, tdate:{action: :create} do |f| %>
 <%= render "form", f: f %>
<% end %>

app/views/tweets/show.html.erb
<p>
    <strong>メッセージ</strong>
    <%= @tweet.message %>
</p>

<p>
    <strong>日時 :</strong>
    <%= @tweet.tdate %>
</p>

<%= link_to 'HOME', root_path %>